# Generated by Django 4.2.14 on 2024-09-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0003_contactus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "Liên hệ", "verbose_name_plural": "Contact"},
        ),
    ]
