# Generated by Django 4.2.14 on 2024-08-16 10:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="Sản phẩm mới thiết kế đa dạng", null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="JC Vietnam ltd.co", null=True
            ),
        ),
    ]
