# Generated by Django 4.2.14 on 2024-08-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_product_specifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="mobile",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="core.product",
            ),
        ),
    ]
