# Generated by Django 4.2.14 on 2024-09-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_address_mobile_alter_productreview_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="address",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="email",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="fullname",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="shipping_method",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="state",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="tracking_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="tracking_website_address",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="zipcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="price",
            field=models.DecimalField(
                decimal_places=3, default="100.000", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=3, default="100.000", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="total",
            field=models.DecimalField(
                decimal_places=3, default="100.000", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                decimal_places=3, default="150.000", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=3, default="100.000", max_digits=12
            ),
        ),
    ]
